# Project-wide Gradle settings.

# Настройки JVM: выделим 4GB памяти для стабильной и быстрой работы KSP и мультимодульности
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Ускорение сборки
org.gradle.parallel=true
org.gradle.caching=true

# Базовые стандарты Android и Kotlin
android.useAndroidX=true
kotlin.code.style=official